rest-client:
  pokemon:
    base-url: https://pokeapi.co
    read-timeout: 200
    connect-timeout: 200
  shakespeare-translation:
    base-url: https://api.funtranslations.com
    path: translate/shakespeare.json
    read-timeout: 200
    connect-timeout: 200
  yoda-translation:
    base-url: https://api.funtranslations.com
    path: translate/yoda.json
    read-timeout: 200
    connect-timeout: 200

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 100
      retryExceptionPredicate: org.simor.adapter.client.RestClientRetryPredicate
  instances:
    pokemon:
      baseConfig: default
    translation:
      baseConfig: default