rest-client:
  pokemon:
    base-url: https://pokeapi.co
  shakespeare-translation:
    base-url: https://api.funtranslations.com
    path: translate/shakespeare.json
  yoda-translation:
    base-url: https://api.funtranslations.com
    path: translate/yoda.json