rest-client:
  pokemon:
    base-url: https://pokeapi.co
    read-timeout: 500
    connect-timeout: 500
  shakespeare-translation:
    base-url: https://api.funtranslations.com
    path: translate/shakespeare.json
    read-timeout: 1000
    connect-timeout: 1000
  yoda-translation:
    base-url: https://api.funtranslations.com
    path: translate/yoda.json
    read-timeout: 1000
    connect-timeout: 1000

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 100
      retryExceptionPredicate: org.simor.adapter.client.RestClientRetryPredicate
  instances:
    retry-pokemon:
      baseConfig: default
    retry-translation:
      baseConfig: default

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10000
      failureRateThreshold: 60
      eventConsumerBufferSize: 10
      registerHealthIndicator: true
  instances:
    cb-pokemon:
      baseConfig: default
      recordExceptions: org.simor.adapter.client.PokemonRestClientException
    cb-translation:
      baseConfig: default
      recordExceptions: org.simor.adapter.client.TranslationRestClientException